import { Theme } from "../types/type";

export enum QuestionPrefix {
  A = 1,
  B = 2,
  C = 3,
  D = 4,
  E = 5,
  F = 6,
  G = 7,
}

export enum Mode {
  Normal = 1,
  Practice = 2,
  Revision = 3,
}

export const STYLE = {
  FONT_WEIGHT_NORMAL: "normal",
  FONT_WEIGHT_BOLD: "600",
};

export const THEME: Theme = {
  LIGHT: {
    CIRCLE_NORMAL_COLOR: "#EAEAEA",
    CIRCLE_CORRECT_COLOR: "#307F41",
    CIRCLE_INCORRECT_COLOR: "#DE4A4A",
    BACKGROUND_COLOR_NORMAL: "#f4ff4",
    FONT_COLOR_NORMAL: "#2F2F2F",
    FONT_CORRECT_COLOR: "#2CDA93",
    FONT_INCORRECT_COLOR: "#EE7C6F",
    FONT_CORRECT_ANSWER_COLOR: "#DE3B0F",
    DROPDOWN_BACKGROUND_COLOR_NORMAL: "#f4f4f4",
    DROPDOWN_CORRECT_COLOR: "#91EEB9",
    DROPDOWN_INCORRECT_COLOR: "#ECB0AA",
    FONT_SELECTED_COLOR: "#212121",
    SWITCH_COLOR: "grey",
    SECOND_BACKGROUND_COLOR: "#f4f4f4",
  },
  DARK: {
    CIRCLE_NORMAL_COLOR: "#EAEAEA",
    CIRCLE_CORRECT_COLOR: "#307F41",
    CIRCLE_INCORRECT_COLOR: "#DE4A4A",
    BACKGROUND_COLOR_NORMAL: "#121212",
    FONT_COLOR_NORMAL: "#D9D9D9",
    FONT_CORRECT_COLOR: "#2CDA93",
    FONT_INCORRECT_COLOR: "#EE7C6F",
    FONT_CORRECT_ANSWER_COLOR: "#DE3B0F",
    DROPDOWN_BACKGROUND_COLOR_NORMAL: "#DCDCDC",
    DROPDOWN_CORRECT_COLOR: "#319E60",
    DROPDOWN_INCORRECT_COLOR: "#AC2618",
    FONT_SELECTED_COLOR: "#212121",
    SWITCH_COLOR: "grey",
    SECOND_BACKGROUND_COLOR: "#1A1A1A",
  },
};
